[build]
  command = "npm run build"
  functions = "D:\\Program\\Bajaj Finserv\\bfhl-frontend\\netlify\\functions"
  publish = "build"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200